# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

max_range = 4000000
# max_range = 90
count = 0
before_count = 1
next_count = 1
even_value = 0
while next_count < max_range:
    count = before_count + next_count
    before_count = next_count
    next_count = count
    if count % 2 == 0:
        even_value = even_value + count
        print(f"{count} -> {even_value}")

print(count)
print(even_value)